// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ClientVersionsConfigDTO client versions config d t o
//
// swagger:model ClientVersionsConfigDTO
type ClientVersionsConfigDTO struct {

	// max compatible version
	MaxCompatibleVersion string `json:"maxCompatibleVersion,omitempty"`

	// min compatible version
	MinCompatibleVersion string `json:"minCompatibleVersion,omitempty"`

	// min recommended version
	MinRecommendedVersion string `json:"minRecommendedVersion,omitempty"`
}

// Validate validates this client versions config d t o
func (m *ClientVersionsConfigDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this client versions config d t o based on context it is used
func (m *ClientVersionsConfigDTO) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ClientVersionsConfigDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClientVersionsConfigDTO) UnmarshalBinary(b []byte) error {
	var res ClientVersionsConfigDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
