// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelRegistryLimitsTraitDTO model registry limits trait d t o
//
// swagger:model ModelRegistryLimitsTraitDTO
type ModelRegistryLimitsTraitDTO struct {

	// max models per project
	MaxModelsPerProject int32 `json:"maxModelsPerProject,omitempty"`
}

// Validate validates this model registry limits trait d t o
func (m *ModelRegistryLimitsTraitDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this model registry limits trait d t o based on context it is used
func (m *ModelRegistryLimitsTraitDTO) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelRegistryLimitsTraitDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelRegistryLimitsTraitDTO) UnmarshalBinary(b []byte) error {
	var res ModelRegistryLimitsTraitDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
