// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MonitoringTimeUsageDTO monitoring time usage d t o
//
// swagger:model MonitoringTimeUsageDTO
type MonitoringTimeUsageDTO struct {

	// last30 days seconds
	// Required: true
	Last30DaysSeconds *int64 `json:"last30DaysSeconds"`

	// total seconds
	// Required: true
	TotalSeconds *int64 `json:"totalSeconds"`
}

// Validate validates this monitoring time usage d t o
func (m *MonitoringTimeUsageDTO) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLast30DaysSeconds(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTotalSeconds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MonitoringTimeUsageDTO) validateLast30DaysSeconds(formats strfmt.Registry) error {

	if err := validate.Required("last30DaysSeconds", "body", m.Last30DaysSeconds); err != nil {
		return err
	}

	return nil
}

func (m *MonitoringTimeUsageDTO) validateTotalSeconds(formats strfmt.Registry) error {

	if err := validate.Required("totalSeconds", "body", m.TotalSeconds); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this monitoring time usage d t o based on context it is used
func (m *MonitoringTimeUsageDTO) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MonitoringTimeUsageDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MonitoringTimeUsageDTO) UnmarshalBinary(b []byte) error {
	var res MonitoringTimeUsageDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
