// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OrganizationCreationParamsDTO organization creation params d t o
//
// swagger:model OrganizationCreationParamsDTO
type OrganizationCreationParamsDTO struct {

	// organization name
	// Required: true
	OrganizationName *string `json:"organizationName"`

	// pricing plan
	// Required: true
	PricingPlan *PricingPlanDTO `json:"pricingPlan"`
}

// Validate validates this organization creation params d t o
func (m *OrganizationCreationParamsDTO) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOrganizationName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePricingPlan(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrganizationCreationParamsDTO) validateOrganizationName(formats strfmt.Registry) error {

	if err := validate.Required("organizationName", "body", m.OrganizationName); err != nil {
		return err
	}

	return nil
}

func (m *OrganizationCreationParamsDTO) validatePricingPlan(formats strfmt.Registry) error {

	if err := validate.Required("pricingPlan", "body", m.PricingPlan); err != nil {
		return err
	}

	if err := validate.Required("pricingPlan", "body", m.PricingPlan); err != nil {
		return err
	}

	if m.PricingPlan != nil {
		if err := m.PricingPlan.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pricingPlan")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("pricingPlan")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this organization creation params d t o based on the context it is used
func (m *OrganizationCreationParamsDTO) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePricingPlan(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrganizationCreationParamsDTO) contextValidatePricingPlan(ctx context.Context, formats strfmt.Registry) error {

	if m.PricingPlan != nil {

		if err := m.PricingPlan.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pricingPlan")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("pricingPlan")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OrganizationCreationParamsDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrganizationCreationParamsDTO) UnmarshalBinary(b []byte) error {
	var res OrganizationCreationParamsDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
