// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"terraform-provider-neptune/internal/neptune/models"
)

// CreateOrganizationInvitationsReader is a Reader for the CreateOrganizationInvitations structure.
type CreateOrganizationInvitationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateOrganizationInvitationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateOrganizationInvitationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateOrganizationInvitationsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateOrganizationInvitationsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateOrganizationInvitationsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateOrganizationInvitationsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 408:
		result := NewCreateOrganizationInvitationsRequestTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewCreateOrganizationInvitationsUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/backend/v1/invitations/organization] createOrganizationInvitations", response, response.Code())
	}
}

// NewCreateOrganizationInvitationsOK creates a CreateOrganizationInvitationsOK with default headers values
func NewCreateOrganizationInvitationsOK() *CreateOrganizationInvitationsOK {
	return &CreateOrganizationInvitationsOK{}
}

/*
CreateOrganizationInvitationsOK describes a response with status code 200, with default header values.

OK
*/
type CreateOrganizationInvitationsOK struct {
	Payload *models.OrganizationInvitationsDTO
}

// IsSuccess returns true when this create organization invitations o k response has a 2xx status code
func (o *CreateOrganizationInvitationsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create organization invitations o k response has a 3xx status code
func (o *CreateOrganizationInvitationsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create organization invitations o k response has a 4xx status code
func (o *CreateOrganizationInvitationsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create organization invitations o k response has a 5xx status code
func (o *CreateOrganizationInvitationsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create organization invitations o k response a status code equal to that given
func (o *CreateOrganizationInvitationsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create organization invitations o k response
func (o *CreateOrganizationInvitationsOK) Code() int {
	return 200
}

func (o *CreateOrganizationInvitationsOK) Error() string {
	return fmt.Sprintf("[POST /api/backend/v1/invitations/organization][%d] createOrganizationInvitationsOK  %+v", 200, o.Payload)
}

func (o *CreateOrganizationInvitationsOK) String() string {
	return fmt.Sprintf("[POST /api/backend/v1/invitations/organization][%d] createOrganizationInvitationsOK  %+v", 200, o.Payload)
}

func (o *CreateOrganizationInvitationsOK) GetPayload() *models.OrganizationInvitationsDTO {
	return o.Payload
}

func (o *CreateOrganizationInvitationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OrganizationInvitationsDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateOrganizationInvitationsBadRequest creates a CreateOrganizationInvitationsBadRequest with default headers values
func NewCreateOrganizationInvitationsBadRequest() *CreateOrganizationInvitationsBadRequest {
	return &CreateOrganizationInvitationsBadRequest{}
}

/*
CreateOrganizationInvitationsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CreateOrganizationInvitationsBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this create organization invitations bad request response has a 2xx status code
func (o *CreateOrganizationInvitationsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create organization invitations bad request response has a 3xx status code
func (o *CreateOrganizationInvitationsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create organization invitations bad request response has a 4xx status code
func (o *CreateOrganizationInvitationsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create organization invitations bad request response has a 5xx status code
func (o *CreateOrganizationInvitationsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create organization invitations bad request response a status code equal to that given
func (o *CreateOrganizationInvitationsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create organization invitations bad request response
func (o *CreateOrganizationInvitationsBadRequest) Code() int {
	return 400
}

func (o *CreateOrganizationInvitationsBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/backend/v1/invitations/organization][%d] createOrganizationInvitationsBadRequest  %+v", 400, o.Payload)
}

func (o *CreateOrganizationInvitationsBadRequest) String() string {
	return fmt.Sprintf("[POST /api/backend/v1/invitations/organization][%d] createOrganizationInvitationsBadRequest  %+v", 400, o.Payload)
}

func (o *CreateOrganizationInvitationsBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateOrganizationInvitationsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateOrganizationInvitationsUnauthorized creates a CreateOrganizationInvitationsUnauthorized with default headers values
func NewCreateOrganizationInvitationsUnauthorized() *CreateOrganizationInvitationsUnauthorized {
	return &CreateOrganizationInvitationsUnauthorized{}
}

/*
CreateOrganizationInvitationsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type CreateOrganizationInvitationsUnauthorized struct {
}

// IsSuccess returns true when this create organization invitations unauthorized response has a 2xx status code
func (o *CreateOrganizationInvitationsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create organization invitations unauthorized response has a 3xx status code
func (o *CreateOrganizationInvitationsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create organization invitations unauthorized response has a 4xx status code
func (o *CreateOrganizationInvitationsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create organization invitations unauthorized response has a 5xx status code
func (o *CreateOrganizationInvitationsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create organization invitations unauthorized response a status code equal to that given
func (o *CreateOrganizationInvitationsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the create organization invitations unauthorized response
func (o *CreateOrganizationInvitationsUnauthorized) Code() int {
	return 401
}

func (o *CreateOrganizationInvitationsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/backend/v1/invitations/organization][%d] createOrganizationInvitationsUnauthorized ", 401)
}

func (o *CreateOrganizationInvitationsUnauthorized) String() string {
	return fmt.Sprintf("[POST /api/backend/v1/invitations/organization][%d] createOrganizationInvitationsUnauthorized ", 401)
}

func (o *CreateOrganizationInvitationsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateOrganizationInvitationsForbidden creates a CreateOrganizationInvitationsForbidden with default headers values
func NewCreateOrganizationInvitationsForbidden() *CreateOrganizationInvitationsForbidden {
	return &CreateOrganizationInvitationsForbidden{}
}

/*
CreateOrganizationInvitationsForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type CreateOrganizationInvitationsForbidden struct {
}

// IsSuccess returns true when this create organization invitations forbidden response has a 2xx status code
func (o *CreateOrganizationInvitationsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create organization invitations forbidden response has a 3xx status code
func (o *CreateOrganizationInvitationsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create organization invitations forbidden response has a 4xx status code
func (o *CreateOrganizationInvitationsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create organization invitations forbidden response has a 5xx status code
func (o *CreateOrganizationInvitationsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create organization invitations forbidden response a status code equal to that given
func (o *CreateOrganizationInvitationsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the create organization invitations forbidden response
func (o *CreateOrganizationInvitationsForbidden) Code() int {
	return 403
}

func (o *CreateOrganizationInvitationsForbidden) Error() string {
	return fmt.Sprintf("[POST /api/backend/v1/invitations/organization][%d] createOrganizationInvitationsForbidden ", 403)
}

func (o *CreateOrganizationInvitationsForbidden) String() string {
	return fmt.Sprintf("[POST /api/backend/v1/invitations/organization][%d] createOrganizationInvitationsForbidden ", 403)
}

func (o *CreateOrganizationInvitationsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateOrganizationInvitationsNotFound creates a CreateOrganizationInvitationsNotFound with default headers values
func NewCreateOrganizationInvitationsNotFound() *CreateOrganizationInvitationsNotFound {
	return &CreateOrganizationInvitationsNotFound{}
}

/*
CreateOrganizationInvitationsNotFound describes a response with status code 404, with default header values.

Not Found
*/
type CreateOrganizationInvitationsNotFound struct {
}

// IsSuccess returns true when this create organization invitations not found response has a 2xx status code
func (o *CreateOrganizationInvitationsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create organization invitations not found response has a 3xx status code
func (o *CreateOrganizationInvitationsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create organization invitations not found response has a 4xx status code
func (o *CreateOrganizationInvitationsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this create organization invitations not found response has a 5xx status code
func (o *CreateOrganizationInvitationsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this create organization invitations not found response a status code equal to that given
func (o *CreateOrganizationInvitationsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the create organization invitations not found response
func (o *CreateOrganizationInvitationsNotFound) Code() int {
	return 404
}

func (o *CreateOrganizationInvitationsNotFound) Error() string {
	return fmt.Sprintf("[POST /api/backend/v1/invitations/organization][%d] createOrganizationInvitationsNotFound ", 404)
}

func (o *CreateOrganizationInvitationsNotFound) String() string {
	return fmt.Sprintf("[POST /api/backend/v1/invitations/organization][%d] createOrganizationInvitationsNotFound ", 404)
}

func (o *CreateOrganizationInvitationsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateOrganizationInvitationsRequestTimeout creates a CreateOrganizationInvitationsRequestTimeout with default headers values
func NewCreateOrganizationInvitationsRequestTimeout() *CreateOrganizationInvitationsRequestTimeout {
	return &CreateOrganizationInvitationsRequestTimeout{}
}

/*
CreateOrganizationInvitationsRequestTimeout describes a response with status code 408, with default header values.

Request Timeout
*/
type CreateOrganizationInvitationsRequestTimeout struct {
}

// IsSuccess returns true when this create organization invitations request timeout response has a 2xx status code
func (o *CreateOrganizationInvitationsRequestTimeout) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create organization invitations request timeout response has a 3xx status code
func (o *CreateOrganizationInvitationsRequestTimeout) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create organization invitations request timeout response has a 4xx status code
func (o *CreateOrganizationInvitationsRequestTimeout) IsClientError() bool {
	return true
}

// IsServerError returns true when this create organization invitations request timeout response has a 5xx status code
func (o *CreateOrganizationInvitationsRequestTimeout) IsServerError() bool {
	return false
}

// IsCode returns true when this create organization invitations request timeout response a status code equal to that given
func (o *CreateOrganizationInvitationsRequestTimeout) IsCode(code int) bool {
	return code == 408
}

// Code gets the status code for the create organization invitations request timeout response
func (o *CreateOrganizationInvitationsRequestTimeout) Code() int {
	return 408
}

func (o *CreateOrganizationInvitationsRequestTimeout) Error() string {
	return fmt.Sprintf("[POST /api/backend/v1/invitations/organization][%d] createOrganizationInvitationsRequestTimeout ", 408)
}

func (o *CreateOrganizationInvitationsRequestTimeout) String() string {
	return fmt.Sprintf("[POST /api/backend/v1/invitations/organization][%d] createOrganizationInvitationsRequestTimeout ", 408)
}

func (o *CreateOrganizationInvitationsRequestTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateOrganizationInvitationsUnprocessableEntity creates a CreateOrganizationInvitationsUnprocessableEntity with default headers values
func NewCreateOrganizationInvitationsUnprocessableEntity() *CreateOrganizationInvitationsUnprocessableEntity {
	return &CreateOrganizationInvitationsUnprocessableEntity{}
}

/*
CreateOrganizationInvitationsUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable Entity
*/
type CreateOrganizationInvitationsUnprocessableEntity struct {
}

// IsSuccess returns true when this create organization invitations unprocessable entity response has a 2xx status code
func (o *CreateOrganizationInvitationsUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create organization invitations unprocessable entity response has a 3xx status code
func (o *CreateOrganizationInvitationsUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create organization invitations unprocessable entity response has a 4xx status code
func (o *CreateOrganizationInvitationsUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this create organization invitations unprocessable entity response has a 5xx status code
func (o *CreateOrganizationInvitationsUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this create organization invitations unprocessable entity response a status code equal to that given
func (o *CreateOrganizationInvitationsUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the create organization invitations unprocessable entity response
func (o *CreateOrganizationInvitationsUnprocessableEntity) Code() int {
	return 422
}

func (o *CreateOrganizationInvitationsUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /api/backend/v1/invitations/organization][%d] createOrganizationInvitationsUnprocessableEntity ", 422)
}

func (o *CreateOrganizationInvitationsUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /api/backend/v1/invitations/organization][%d] createOrganizationInvitationsUnprocessableEntity ", 422)
}

func (o *CreateOrganizationInvitationsUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
