// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"terraform-provider-neptune/internal/neptune/models"
)

// DeleteOrganizationMemberReader is a Reader for the DeleteOrganizationMember structure.
type DeleteOrganizationMemberReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteOrganizationMemberReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteOrganizationMemberOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteOrganizationMemberBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteOrganizationMemberUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteOrganizationMemberForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteOrganizationMemberNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 408:
		result := NewDeleteOrganizationMemberRequestTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewDeleteOrganizationMemberUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /api/backend/v1/organizations2/{organizationIdentifier}/members/{userId}] deleteOrganizationMember", response, response.Code())
	}
}

// NewDeleteOrganizationMemberOK creates a DeleteOrganizationMemberOK with default headers values
func NewDeleteOrganizationMemberOK() *DeleteOrganizationMemberOK {
	return &DeleteOrganizationMemberOK{}
}

/*
DeleteOrganizationMemberOK describes a response with status code 200, with default header values.

No response
*/
type DeleteOrganizationMemberOK struct {
}

// IsSuccess returns true when this delete organization member o k response has a 2xx status code
func (o *DeleteOrganizationMemberOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete organization member o k response has a 3xx status code
func (o *DeleteOrganizationMemberOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete organization member o k response has a 4xx status code
func (o *DeleteOrganizationMemberOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete organization member o k response has a 5xx status code
func (o *DeleteOrganizationMemberOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete organization member o k response a status code equal to that given
func (o *DeleteOrganizationMemberOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete organization member o k response
func (o *DeleteOrganizationMemberOK) Code() int {
	return 200
}

func (o *DeleteOrganizationMemberOK) Error() string {
	return fmt.Sprintf("[DELETE /api/backend/v1/organizations2/{organizationIdentifier}/members/{userId}][%d] deleteOrganizationMemberOK ", 200)
}

func (o *DeleteOrganizationMemberOK) String() string {
	return fmt.Sprintf("[DELETE /api/backend/v1/organizations2/{organizationIdentifier}/members/{userId}][%d] deleteOrganizationMemberOK ", 200)
}

func (o *DeleteOrganizationMemberOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteOrganizationMemberBadRequest creates a DeleteOrganizationMemberBadRequest with default headers values
func NewDeleteOrganizationMemberBadRequest() *DeleteOrganizationMemberBadRequest {
	return &DeleteOrganizationMemberBadRequest{}
}

/*
DeleteOrganizationMemberBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type DeleteOrganizationMemberBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete organization member bad request response has a 2xx status code
func (o *DeleteOrganizationMemberBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete organization member bad request response has a 3xx status code
func (o *DeleteOrganizationMemberBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete organization member bad request response has a 4xx status code
func (o *DeleteOrganizationMemberBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete organization member bad request response has a 5xx status code
func (o *DeleteOrganizationMemberBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete organization member bad request response a status code equal to that given
func (o *DeleteOrganizationMemberBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete organization member bad request response
func (o *DeleteOrganizationMemberBadRequest) Code() int {
	return 400
}

func (o *DeleteOrganizationMemberBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/backend/v1/organizations2/{organizationIdentifier}/members/{userId}][%d] deleteOrganizationMemberBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteOrganizationMemberBadRequest) String() string {
	return fmt.Sprintf("[DELETE /api/backend/v1/organizations2/{organizationIdentifier}/members/{userId}][%d] deleteOrganizationMemberBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteOrganizationMemberBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteOrganizationMemberBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteOrganizationMemberUnauthorized creates a DeleteOrganizationMemberUnauthorized with default headers values
func NewDeleteOrganizationMemberUnauthorized() *DeleteOrganizationMemberUnauthorized {
	return &DeleteOrganizationMemberUnauthorized{}
}

/*
DeleteOrganizationMemberUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteOrganizationMemberUnauthorized struct {
}

// IsSuccess returns true when this delete organization member unauthorized response has a 2xx status code
func (o *DeleteOrganizationMemberUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete organization member unauthorized response has a 3xx status code
func (o *DeleteOrganizationMemberUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete organization member unauthorized response has a 4xx status code
func (o *DeleteOrganizationMemberUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete organization member unauthorized response has a 5xx status code
func (o *DeleteOrganizationMemberUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete organization member unauthorized response a status code equal to that given
func (o *DeleteOrganizationMemberUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the delete organization member unauthorized response
func (o *DeleteOrganizationMemberUnauthorized) Code() int {
	return 401
}

func (o *DeleteOrganizationMemberUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /api/backend/v1/organizations2/{organizationIdentifier}/members/{userId}][%d] deleteOrganizationMemberUnauthorized ", 401)
}

func (o *DeleteOrganizationMemberUnauthorized) String() string {
	return fmt.Sprintf("[DELETE /api/backend/v1/organizations2/{organizationIdentifier}/members/{userId}][%d] deleteOrganizationMemberUnauthorized ", 401)
}

func (o *DeleteOrganizationMemberUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteOrganizationMemberForbidden creates a DeleteOrganizationMemberForbidden with default headers values
func NewDeleteOrganizationMemberForbidden() *DeleteOrganizationMemberForbidden {
	return &DeleteOrganizationMemberForbidden{}
}

/*
DeleteOrganizationMemberForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type DeleteOrganizationMemberForbidden struct {
}

// IsSuccess returns true when this delete organization member forbidden response has a 2xx status code
func (o *DeleteOrganizationMemberForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete organization member forbidden response has a 3xx status code
func (o *DeleteOrganizationMemberForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete organization member forbidden response has a 4xx status code
func (o *DeleteOrganizationMemberForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete organization member forbidden response has a 5xx status code
func (o *DeleteOrganizationMemberForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this delete organization member forbidden response a status code equal to that given
func (o *DeleteOrganizationMemberForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the delete organization member forbidden response
func (o *DeleteOrganizationMemberForbidden) Code() int {
	return 403
}

func (o *DeleteOrganizationMemberForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api/backend/v1/organizations2/{organizationIdentifier}/members/{userId}][%d] deleteOrganizationMemberForbidden ", 403)
}

func (o *DeleteOrganizationMemberForbidden) String() string {
	return fmt.Sprintf("[DELETE /api/backend/v1/organizations2/{organizationIdentifier}/members/{userId}][%d] deleteOrganizationMemberForbidden ", 403)
}

func (o *DeleteOrganizationMemberForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteOrganizationMemberNotFound creates a DeleteOrganizationMemberNotFound with default headers values
func NewDeleteOrganizationMemberNotFound() *DeleteOrganizationMemberNotFound {
	return &DeleteOrganizationMemberNotFound{}
}

/*
DeleteOrganizationMemberNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteOrganizationMemberNotFound struct {
}

// IsSuccess returns true when this delete organization member not found response has a 2xx status code
func (o *DeleteOrganizationMemberNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete organization member not found response has a 3xx status code
func (o *DeleteOrganizationMemberNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete organization member not found response has a 4xx status code
func (o *DeleteOrganizationMemberNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete organization member not found response has a 5xx status code
func (o *DeleteOrganizationMemberNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete organization member not found response a status code equal to that given
func (o *DeleteOrganizationMemberNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete organization member not found response
func (o *DeleteOrganizationMemberNotFound) Code() int {
	return 404
}

func (o *DeleteOrganizationMemberNotFound) Error() string {
	return fmt.Sprintf("[DELETE /api/backend/v1/organizations2/{organizationIdentifier}/members/{userId}][%d] deleteOrganizationMemberNotFound ", 404)
}

func (o *DeleteOrganizationMemberNotFound) String() string {
	return fmt.Sprintf("[DELETE /api/backend/v1/organizations2/{organizationIdentifier}/members/{userId}][%d] deleteOrganizationMemberNotFound ", 404)
}

func (o *DeleteOrganizationMemberNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteOrganizationMemberRequestTimeout creates a DeleteOrganizationMemberRequestTimeout with default headers values
func NewDeleteOrganizationMemberRequestTimeout() *DeleteOrganizationMemberRequestTimeout {
	return &DeleteOrganizationMemberRequestTimeout{}
}

/*
DeleteOrganizationMemberRequestTimeout describes a response with status code 408, with default header values.

Request Timeout
*/
type DeleteOrganizationMemberRequestTimeout struct {
}

// IsSuccess returns true when this delete organization member request timeout response has a 2xx status code
func (o *DeleteOrganizationMemberRequestTimeout) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete organization member request timeout response has a 3xx status code
func (o *DeleteOrganizationMemberRequestTimeout) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete organization member request timeout response has a 4xx status code
func (o *DeleteOrganizationMemberRequestTimeout) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete organization member request timeout response has a 5xx status code
func (o *DeleteOrganizationMemberRequestTimeout) IsServerError() bool {
	return false
}

// IsCode returns true when this delete organization member request timeout response a status code equal to that given
func (o *DeleteOrganizationMemberRequestTimeout) IsCode(code int) bool {
	return code == 408
}

// Code gets the status code for the delete organization member request timeout response
func (o *DeleteOrganizationMemberRequestTimeout) Code() int {
	return 408
}

func (o *DeleteOrganizationMemberRequestTimeout) Error() string {
	return fmt.Sprintf("[DELETE /api/backend/v1/organizations2/{organizationIdentifier}/members/{userId}][%d] deleteOrganizationMemberRequestTimeout ", 408)
}

func (o *DeleteOrganizationMemberRequestTimeout) String() string {
	return fmt.Sprintf("[DELETE /api/backend/v1/organizations2/{organizationIdentifier}/members/{userId}][%d] deleteOrganizationMemberRequestTimeout ", 408)
}

func (o *DeleteOrganizationMemberRequestTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteOrganizationMemberUnprocessableEntity creates a DeleteOrganizationMemberUnprocessableEntity with default headers values
func NewDeleteOrganizationMemberUnprocessableEntity() *DeleteOrganizationMemberUnprocessableEntity {
	return &DeleteOrganizationMemberUnprocessableEntity{}
}

/*
DeleteOrganizationMemberUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable Entity
*/
type DeleteOrganizationMemberUnprocessableEntity struct {
}

// IsSuccess returns true when this delete organization member unprocessable entity response has a 2xx status code
func (o *DeleteOrganizationMemberUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete organization member unprocessable entity response has a 3xx status code
func (o *DeleteOrganizationMemberUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete organization member unprocessable entity response has a 4xx status code
func (o *DeleteOrganizationMemberUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete organization member unprocessable entity response has a 5xx status code
func (o *DeleteOrganizationMemberUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this delete organization member unprocessable entity response a status code equal to that given
func (o *DeleteOrganizationMemberUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the delete organization member unprocessable entity response
func (o *DeleteOrganizationMemberUnprocessableEntity) Code() int {
	return 422
}

func (o *DeleteOrganizationMemberUnprocessableEntity) Error() string {
	return fmt.Sprintf("[DELETE /api/backend/v1/organizations2/{organizationIdentifier}/members/{userId}][%d] deleteOrganizationMemberUnprocessableEntity ", 422)
}

func (o *DeleteOrganizationMemberUnprocessableEntity) String() string {
	return fmt.Sprintf("[DELETE /api/backend/v1/organizations2/{organizationIdentifier}/members/{userId}][%d] deleteOrganizationMemberUnprocessableEntity ", 422)
}

func (o *DeleteOrganizationMemberUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
