// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"terraform-provider-neptune/internal/neptune/models"
)

// DeleteOrganizationReader is a Reader for the DeleteOrganization structure.
type DeleteOrganizationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteOrganizationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteOrganizationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteOrganizationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteOrganizationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteOrganizationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteOrganizationNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 408:
		result := NewDeleteOrganizationRequestTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewDeleteOrganizationUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /api/backend/v1/organizations2/{organizationId}] deleteOrganization", response, response.Code())
	}
}

// NewDeleteOrganizationOK creates a DeleteOrganizationOK with default headers values
func NewDeleteOrganizationOK() *DeleteOrganizationOK {
	return &DeleteOrganizationOK{}
}

/*
DeleteOrganizationOK describes a response with status code 200, with default header values.

No response
*/
type DeleteOrganizationOK struct {
}

// IsSuccess returns true when this delete organization o k response has a 2xx status code
func (o *DeleteOrganizationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete organization o k response has a 3xx status code
func (o *DeleteOrganizationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete organization o k response has a 4xx status code
func (o *DeleteOrganizationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete organization o k response has a 5xx status code
func (o *DeleteOrganizationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete organization o k response a status code equal to that given
func (o *DeleteOrganizationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete organization o k response
func (o *DeleteOrganizationOK) Code() int {
	return 200
}

func (o *DeleteOrganizationOK) Error() string {
	return fmt.Sprintf("[DELETE /api/backend/v1/organizations2/{organizationId}][%d] deleteOrganizationOK ", 200)
}

func (o *DeleteOrganizationOK) String() string {
	return fmt.Sprintf("[DELETE /api/backend/v1/organizations2/{organizationId}][%d] deleteOrganizationOK ", 200)
}

func (o *DeleteOrganizationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteOrganizationBadRequest creates a DeleteOrganizationBadRequest with default headers values
func NewDeleteOrganizationBadRequest() *DeleteOrganizationBadRequest {
	return &DeleteOrganizationBadRequest{}
}

/*
DeleteOrganizationBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type DeleteOrganizationBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete organization bad request response has a 2xx status code
func (o *DeleteOrganizationBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete organization bad request response has a 3xx status code
func (o *DeleteOrganizationBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete organization bad request response has a 4xx status code
func (o *DeleteOrganizationBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete organization bad request response has a 5xx status code
func (o *DeleteOrganizationBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete organization bad request response a status code equal to that given
func (o *DeleteOrganizationBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete organization bad request response
func (o *DeleteOrganizationBadRequest) Code() int {
	return 400
}

func (o *DeleteOrganizationBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/backend/v1/organizations2/{organizationId}][%d] deleteOrganizationBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteOrganizationBadRequest) String() string {
	return fmt.Sprintf("[DELETE /api/backend/v1/organizations2/{organizationId}][%d] deleteOrganizationBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteOrganizationBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteOrganizationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteOrganizationUnauthorized creates a DeleteOrganizationUnauthorized with default headers values
func NewDeleteOrganizationUnauthorized() *DeleteOrganizationUnauthorized {
	return &DeleteOrganizationUnauthorized{}
}

/*
DeleteOrganizationUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteOrganizationUnauthorized struct {
}

// IsSuccess returns true when this delete organization unauthorized response has a 2xx status code
func (o *DeleteOrganizationUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete organization unauthorized response has a 3xx status code
func (o *DeleteOrganizationUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete organization unauthorized response has a 4xx status code
func (o *DeleteOrganizationUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete organization unauthorized response has a 5xx status code
func (o *DeleteOrganizationUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete organization unauthorized response a status code equal to that given
func (o *DeleteOrganizationUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the delete organization unauthorized response
func (o *DeleteOrganizationUnauthorized) Code() int {
	return 401
}

func (o *DeleteOrganizationUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /api/backend/v1/organizations2/{organizationId}][%d] deleteOrganizationUnauthorized ", 401)
}

func (o *DeleteOrganizationUnauthorized) String() string {
	return fmt.Sprintf("[DELETE /api/backend/v1/organizations2/{organizationId}][%d] deleteOrganizationUnauthorized ", 401)
}

func (o *DeleteOrganizationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteOrganizationForbidden creates a DeleteOrganizationForbidden with default headers values
func NewDeleteOrganizationForbidden() *DeleteOrganizationForbidden {
	return &DeleteOrganizationForbidden{}
}

/*
DeleteOrganizationForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type DeleteOrganizationForbidden struct {
}

// IsSuccess returns true when this delete organization forbidden response has a 2xx status code
func (o *DeleteOrganizationForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete organization forbidden response has a 3xx status code
func (o *DeleteOrganizationForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete organization forbidden response has a 4xx status code
func (o *DeleteOrganizationForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete organization forbidden response has a 5xx status code
func (o *DeleteOrganizationForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this delete organization forbidden response a status code equal to that given
func (o *DeleteOrganizationForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the delete organization forbidden response
func (o *DeleteOrganizationForbidden) Code() int {
	return 403
}

func (o *DeleteOrganizationForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api/backend/v1/organizations2/{organizationId}][%d] deleteOrganizationForbidden ", 403)
}

func (o *DeleteOrganizationForbidden) String() string {
	return fmt.Sprintf("[DELETE /api/backend/v1/organizations2/{organizationId}][%d] deleteOrganizationForbidden ", 403)
}

func (o *DeleteOrganizationForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteOrganizationNotFound creates a DeleteOrganizationNotFound with default headers values
func NewDeleteOrganizationNotFound() *DeleteOrganizationNotFound {
	return &DeleteOrganizationNotFound{}
}

/*
DeleteOrganizationNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteOrganizationNotFound struct {
}

// IsSuccess returns true when this delete organization not found response has a 2xx status code
func (o *DeleteOrganizationNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete organization not found response has a 3xx status code
func (o *DeleteOrganizationNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete organization not found response has a 4xx status code
func (o *DeleteOrganizationNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete organization not found response has a 5xx status code
func (o *DeleteOrganizationNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete organization not found response a status code equal to that given
func (o *DeleteOrganizationNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete organization not found response
func (o *DeleteOrganizationNotFound) Code() int {
	return 404
}

func (o *DeleteOrganizationNotFound) Error() string {
	return fmt.Sprintf("[DELETE /api/backend/v1/organizations2/{organizationId}][%d] deleteOrganizationNotFound ", 404)
}

func (o *DeleteOrganizationNotFound) String() string {
	return fmt.Sprintf("[DELETE /api/backend/v1/organizations2/{organizationId}][%d] deleteOrganizationNotFound ", 404)
}

func (o *DeleteOrganizationNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteOrganizationRequestTimeout creates a DeleteOrganizationRequestTimeout with default headers values
func NewDeleteOrganizationRequestTimeout() *DeleteOrganizationRequestTimeout {
	return &DeleteOrganizationRequestTimeout{}
}

/*
DeleteOrganizationRequestTimeout describes a response with status code 408, with default header values.

Request Timeout
*/
type DeleteOrganizationRequestTimeout struct {
}

// IsSuccess returns true when this delete organization request timeout response has a 2xx status code
func (o *DeleteOrganizationRequestTimeout) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete organization request timeout response has a 3xx status code
func (o *DeleteOrganizationRequestTimeout) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete organization request timeout response has a 4xx status code
func (o *DeleteOrganizationRequestTimeout) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete organization request timeout response has a 5xx status code
func (o *DeleteOrganizationRequestTimeout) IsServerError() bool {
	return false
}

// IsCode returns true when this delete organization request timeout response a status code equal to that given
func (o *DeleteOrganizationRequestTimeout) IsCode(code int) bool {
	return code == 408
}

// Code gets the status code for the delete organization request timeout response
func (o *DeleteOrganizationRequestTimeout) Code() int {
	return 408
}

func (o *DeleteOrganizationRequestTimeout) Error() string {
	return fmt.Sprintf("[DELETE /api/backend/v1/organizations2/{organizationId}][%d] deleteOrganizationRequestTimeout ", 408)
}

func (o *DeleteOrganizationRequestTimeout) String() string {
	return fmt.Sprintf("[DELETE /api/backend/v1/organizations2/{organizationId}][%d] deleteOrganizationRequestTimeout ", 408)
}

func (o *DeleteOrganizationRequestTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteOrganizationUnprocessableEntity creates a DeleteOrganizationUnprocessableEntity with default headers values
func NewDeleteOrganizationUnprocessableEntity() *DeleteOrganizationUnprocessableEntity {
	return &DeleteOrganizationUnprocessableEntity{}
}

/*
DeleteOrganizationUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable Entity
*/
type DeleteOrganizationUnprocessableEntity struct {
}

// IsSuccess returns true when this delete organization unprocessable entity response has a 2xx status code
func (o *DeleteOrganizationUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete organization unprocessable entity response has a 3xx status code
func (o *DeleteOrganizationUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete organization unprocessable entity response has a 4xx status code
func (o *DeleteOrganizationUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete organization unprocessable entity response has a 5xx status code
func (o *DeleteOrganizationUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this delete organization unprocessable entity response a status code equal to that given
func (o *DeleteOrganizationUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the delete organization unprocessable entity response
func (o *DeleteOrganizationUnprocessableEntity) Code() int {
	return 422
}

func (o *DeleteOrganizationUnprocessableEntity) Error() string {
	return fmt.Sprintf("[DELETE /api/backend/v1/organizations2/{organizationId}][%d] deleteOrganizationUnprocessableEntity ", 422)
}

func (o *DeleteOrganizationUnprocessableEntity) String() string {
	return fmt.Sprintf("[DELETE /api/backend/v1/organizations2/{organizationId}][%d] deleteOrganizationUnprocessableEntity ", 422)
}

func (o *DeleteOrganizationUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
