// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteProjectMemberParams creates a new DeleteProjectMemberParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteProjectMemberParams() *DeleteProjectMemberParams {
	return &DeleteProjectMemberParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteProjectMemberParamsWithTimeout creates a new DeleteProjectMemberParams object
// with the ability to set a timeout on a request.
func NewDeleteProjectMemberParamsWithTimeout(timeout time.Duration) *DeleteProjectMemberParams {
	return &DeleteProjectMemberParams{
		timeout: timeout,
	}
}

// NewDeleteProjectMemberParamsWithContext creates a new DeleteProjectMemberParams object
// with the ability to set a context for a request.
func NewDeleteProjectMemberParamsWithContext(ctx context.Context) *DeleteProjectMemberParams {
	return &DeleteProjectMemberParams{
		Context: ctx,
	}
}

// NewDeleteProjectMemberParamsWithHTTPClient creates a new DeleteProjectMemberParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteProjectMemberParamsWithHTTPClient(client *http.Client) *DeleteProjectMemberParams {
	return &DeleteProjectMemberParams{
		HTTPClient: client,
	}
}

/*
DeleteProjectMemberParams contains all the parameters to send to the API endpoint

	for the delete project member operation.

	Typically these are written to a http.Request.
*/
type DeleteProjectMemberParams struct {

	// ProjectIdentifier.
	ProjectIdentifier string

	// UserID.
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete project member params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteProjectMemberParams) WithDefaults() *DeleteProjectMemberParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete project member params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteProjectMemberParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete project member params
func (o *DeleteProjectMemberParams) WithTimeout(timeout time.Duration) *DeleteProjectMemberParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete project member params
func (o *DeleteProjectMemberParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete project member params
func (o *DeleteProjectMemberParams) WithContext(ctx context.Context) *DeleteProjectMemberParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete project member params
func (o *DeleteProjectMemberParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete project member params
func (o *DeleteProjectMemberParams) WithHTTPClient(client *http.Client) *DeleteProjectMemberParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete project member params
func (o *DeleteProjectMemberParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProjectIdentifier adds the projectIdentifier to the delete project member params
func (o *DeleteProjectMemberParams) WithProjectIdentifier(projectIdentifier string) *DeleteProjectMemberParams {
	o.SetProjectIdentifier(projectIdentifier)
	return o
}

// SetProjectIdentifier adds the projectIdentifier to the delete project member params
func (o *DeleteProjectMemberParams) SetProjectIdentifier(projectIdentifier string) {
	o.ProjectIdentifier = projectIdentifier
}

// WithUserID adds the userID to the delete project member params
func (o *DeleteProjectMemberParams) WithUserID(userID string) *DeleteProjectMemberParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the delete project member params
func (o *DeleteProjectMemberParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteProjectMemberParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param projectIdentifier
	qrProjectIdentifier := o.ProjectIdentifier
	qProjectIdentifier := qrProjectIdentifier
	if qProjectIdentifier != "" {

		if err := r.SetQueryParam("projectIdentifier", qProjectIdentifier); err != nil {
			return err
		}
	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
