// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetOrganizationAvatarParams creates a new GetOrganizationAvatarParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetOrganizationAvatarParams() *GetOrganizationAvatarParams {
	return &GetOrganizationAvatarParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrganizationAvatarParamsWithTimeout creates a new GetOrganizationAvatarParams object
// with the ability to set a timeout on a request.
func NewGetOrganizationAvatarParamsWithTimeout(timeout time.Duration) *GetOrganizationAvatarParams {
	return &GetOrganizationAvatarParams{
		timeout: timeout,
	}
}

// NewGetOrganizationAvatarParamsWithContext creates a new GetOrganizationAvatarParams object
// with the ability to set a context for a request.
func NewGetOrganizationAvatarParamsWithContext(ctx context.Context) *GetOrganizationAvatarParams {
	return &GetOrganizationAvatarParams{
		Context: ctx,
	}
}

// NewGetOrganizationAvatarParamsWithHTTPClient creates a new GetOrganizationAvatarParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetOrganizationAvatarParamsWithHTTPClient(client *http.Client) *GetOrganizationAvatarParams {
	return &GetOrganizationAvatarParams{
		HTTPClient: client,
	}
}

/*
GetOrganizationAvatarParams contains all the parameters to send to the API endpoint

	for the get organization avatar operation.

	Typically these are written to a http.Request.
*/
type GetOrganizationAvatarParams struct {

	// OrganizationName.
	OrganizationName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get organization avatar params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrganizationAvatarParams) WithDefaults() *GetOrganizationAvatarParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get organization avatar params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrganizationAvatarParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get organization avatar params
func (o *GetOrganizationAvatarParams) WithTimeout(timeout time.Duration) *GetOrganizationAvatarParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get organization avatar params
func (o *GetOrganizationAvatarParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get organization avatar params
func (o *GetOrganizationAvatarParams) WithContext(ctx context.Context) *GetOrganizationAvatarParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get organization avatar params
func (o *GetOrganizationAvatarParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get organization avatar params
func (o *GetOrganizationAvatarParams) WithHTTPClient(client *http.Client) *GetOrganizationAvatarParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get organization avatar params
func (o *GetOrganizationAvatarParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganizationName adds the organizationName to the get organization avatar params
func (o *GetOrganizationAvatarParams) WithOrganizationName(organizationName string) *GetOrganizationAvatarParams {
	o.SetOrganizationName(organizationName)
	return o
}

// SetOrganizationName adds the organizationName to the get organization avatar params
func (o *GetOrganizationAvatarParams) SetOrganizationName(organizationName string) {
	o.OrganizationName = organizationName
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrganizationAvatarParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organizationName
	if err := r.SetPathParam("organizationName", o.OrganizationName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
