// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListOrganizationProjectsParams creates a new ListOrganizationProjectsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListOrganizationProjectsParams() *ListOrganizationProjectsParams {
	return &ListOrganizationProjectsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListOrganizationProjectsParamsWithTimeout creates a new ListOrganizationProjectsParams object
// with the ability to set a timeout on a request.
func NewListOrganizationProjectsParamsWithTimeout(timeout time.Duration) *ListOrganizationProjectsParams {
	return &ListOrganizationProjectsParams{
		timeout: timeout,
	}
}

// NewListOrganizationProjectsParamsWithContext creates a new ListOrganizationProjectsParams object
// with the ability to set a context for a request.
func NewListOrganizationProjectsParamsWithContext(ctx context.Context) *ListOrganizationProjectsParams {
	return &ListOrganizationProjectsParams{
		Context: ctx,
	}
}

// NewListOrganizationProjectsParamsWithHTTPClient creates a new ListOrganizationProjectsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListOrganizationProjectsParamsWithHTTPClient(client *http.Client) *ListOrganizationProjectsParams {
	return &ListOrganizationProjectsParams{
		HTTPClient: client,
	}
}

/*
ListOrganizationProjectsParams contains all the parameters to send to the API endpoint

	for the list organization projects operation.

	Typically these are written to a http.Request.
*/
type ListOrganizationProjectsParams struct {

	// Archived.
	Archived *bool

	// Limit.
	//
	// Format: int32
	Limit *int32

	// Offset.
	//
	// Format: int32
	Offset *int32

	// OrganizationIdentifier.
	OrganizationIdentifier string

	// SearchTerm.
	SearchTerm *string

	// SortBy.
	SortBy []string

	// SortDirection.
	SortDirection []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list organization projects params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListOrganizationProjectsParams) WithDefaults() *ListOrganizationProjectsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list organization projects params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListOrganizationProjectsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list organization projects params
func (o *ListOrganizationProjectsParams) WithTimeout(timeout time.Duration) *ListOrganizationProjectsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list organization projects params
func (o *ListOrganizationProjectsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list organization projects params
func (o *ListOrganizationProjectsParams) WithContext(ctx context.Context) *ListOrganizationProjectsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list organization projects params
func (o *ListOrganizationProjectsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list organization projects params
func (o *ListOrganizationProjectsParams) WithHTTPClient(client *http.Client) *ListOrganizationProjectsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list organization projects params
func (o *ListOrganizationProjectsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArchived adds the archived to the list organization projects params
func (o *ListOrganizationProjectsParams) WithArchived(archived *bool) *ListOrganizationProjectsParams {
	o.SetArchived(archived)
	return o
}

// SetArchived adds the archived to the list organization projects params
func (o *ListOrganizationProjectsParams) SetArchived(archived *bool) {
	o.Archived = archived
}

// WithLimit adds the limit to the list organization projects params
func (o *ListOrganizationProjectsParams) WithLimit(limit *int32) *ListOrganizationProjectsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the list organization projects params
func (o *ListOrganizationProjectsParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithOffset adds the offset to the list organization projects params
func (o *ListOrganizationProjectsParams) WithOffset(offset *int32) *ListOrganizationProjectsParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the list organization projects params
func (o *ListOrganizationProjectsParams) SetOffset(offset *int32) {
	o.Offset = offset
}

// WithOrganizationIdentifier adds the organizationIdentifier to the list organization projects params
func (o *ListOrganizationProjectsParams) WithOrganizationIdentifier(organizationIdentifier string) *ListOrganizationProjectsParams {
	o.SetOrganizationIdentifier(organizationIdentifier)
	return o
}

// SetOrganizationIdentifier adds the organizationIdentifier to the list organization projects params
func (o *ListOrganizationProjectsParams) SetOrganizationIdentifier(organizationIdentifier string) {
	o.OrganizationIdentifier = organizationIdentifier
}

// WithSearchTerm adds the searchTerm to the list organization projects params
func (o *ListOrganizationProjectsParams) WithSearchTerm(searchTerm *string) *ListOrganizationProjectsParams {
	o.SetSearchTerm(searchTerm)
	return o
}

// SetSearchTerm adds the searchTerm to the list organization projects params
func (o *ListOrganizationProjectsParams) SetSearchTerm(searchTerm *string) {
	o.SearchTerm = searchTerm
}

// WithSortBy adds the sortBy to the list organization projects params
func (o *ListOrganizationProjectsParams) WithSortBy(sortBy []string) *ListOrganizationProjectsParams {
	o.SetSortBy(sortBy)
	return o
}

// SetSortBy adds the sortBy to the list organization projects params
func (o *ListOrganizationProjectsParams) SetSortBy(sortBy []string) {
	o.SortBy = sortBy
}

// WithSortDirection adds the sortDirection to the list organization projects params
func (o *ListOrganizationProjectsParams) WithSortDirection(sortDirection []string) *ListOrganizationProjectsParams {
	o.SetSortDirection(sortDirection)
	return o
}

// SetSortDirection adds the sortDirection to the list organization projects params
func (o *ListOrganizationProjectsParams) SetSortDirection(sortDirection []string) {
	o.SortDirection = sortDirection
}

// WriteToRequest writes these params to a swagger request
func (o *ListOrganizationProjectsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Archived != nil {

		// query param archived
		var qrArchived bool

		if o.Archived != nil {
			qrArchived = *o.Archived
		}
		qArchived := swag.FormatBool(qrArchived)
		if qArchived != "" {

			if err := r.SetQueryParam("archived", qArchived); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int32

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int32

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt32(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	// query param organizationIdentifier
	qrOrganizationIdentifier := o.OrganizationIdentifier
	qOrganizationIdentifier := qrOrganizationIdentifier
	if qOrganizationIdentifier != "" {

		if err := r.SetQueryParam("organizationIdentifier", qOrganizationIdentifier); err != nil {
			return err
		}
	}

	if o.SearchTerm != nil {

		// query param searchTerm
		var qrSearchTerm string

		if o.SearchTerm != nil {
			qrSearchTerm = *o.SearchTerm
		}
		qSearchTerm := qrSearchTerm
		if qSearchTerm != "" {

			if err := r.SetQueryParam("searchTerm", qSearchTerm); err != nil {
				return err
			}
		}
	}

	if o.SortBy != nil {

		// binding items for sortBy
		joinedSortBy := o.bindParamSortBy(reg)

		// query array param sortBy
		if err := r.SetQueryParam("sortBy", joinedSortBy...); err != nil {
			return err
		}
	}

	if o.SortDirection != nil {

		// binding items for sortDirection
		joinedSortDirection := o.bindParamSortDirection(reg)

		// query array param sortDirection
		if err := r.SetQueryParam("sortDirection", joinedSortDirection...); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamListOrganizationProjects binds the parameter sortBy
func (o *ListOrganizationProjectsParams) bindParamSortBy(formats strfmt.Registry) []string {
	sortByIR := o.SortBy

	var sortByIC []string
	for _, sortByIIR := range sortByIR { // explode []string

		sortByIIV := sortByIIR // string as string
		sortByIC = append(sortByIC, sortByIIV)
	}

	// items.CollectionFormat: "multi"
	sortByIS := swag.JoinByFormat(sortByIC, "multi")

	return sortByIS
}

// bindParamListOrganizationProjects binds the parameter sortDirection
func (o *ListOrganizationProjectsParams) bindParamSortDirection(formats strfmt.Registry) []string {
	sortDirectionIR := o.SortDirection

	var sortDirectionIC []string
	for _, sortDirectionIIR := range sortDirectionIR { // explode []string

		sortDirectionIIV := sortDirectionIIR // string as string
		sortDirectionIC = append(sortDirectionIC, sortDirectionIIV)
	}

	// items.CollectionFormat: "multi"
	sortDirectionIS := swag.JoinByFormat(sortDirectionIC, "multi")

	return sortDirectionIS
}
